codecov:
  branch: main
coverage:
  status:
    project:
      default:
        # basic
        target: auto #default
        threshold: 5
        base: auto
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: true
    patch: off
